# Optional; if authentication is kept
apiVersion: v1
kind: Secret
metadata:
  name: helm-api-basic-auth
  namespace: kube-system
type: kubernetes.io/basic-auth
stringData:
  username: helm-api-user
  password: <<secret>>
